name: Ruby CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:

    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: ["ubuntu"]
        ruby-version: [2.7.0, 2.6.0, 2.5.0]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby-version }}
      run: |
        echo $GITHUB_PATH
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby-version }}