name: Ruby CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:

    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: ["ubuntu", "macos"]
        ruby-version: [2.7.0, 2.6.0, 2.5.0]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: Test help
      run: ruby ArkDoc.rb -h